Repository Dev-FE-2/toy-project2-team4-dayus, pull requests merged in 2024-11, with the labels that each got.

#6 [FEAT] 라우터 설정, 기본 레이아웃을 구성합니다.
  .gitignore
  eslint.config.js
  package-lock.json
  package.json
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Regular.woff2
  src/App.css
  src/App.tsx
  src/constants/constant.ts
  src/index.css
  src/layout/Layout.styles.ts
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/.gitkeep
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SalaryPage.tsx
  src/routes/.gitkeep
  src/routes/Router.tsx
  src/styles/.gitkeep
  src/styles/GlobalStyles.ts
  src/styles/design-tokens.css
  src/styles/font.css
  tsconfig.app.json
  vite.config.ts
Labels: 🔧 CHORE, 💻 FE, 🚀 FEAT

#14 #13 [chore] msw 세팅
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/node.ts
Labels: 🔧 CHORE

#12 #7 [FEAT] 버튼 UI 컴포넌트와 not-found 페이지를 퍼블리싱합니다.
  src/assets/not-found.svg
  src/components/.gitkeep
  src/components/ui/Button/Button.tsx
  src/pages/NotFoundPage.tsx
  src/pages/not-found/NotFound.styles.ts
  src/pages/not-found/NotFoundPage.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyles.ts
  src/styles/design-tokens.css
Labels: 💻 FE, 🚀 FEAT

#15 #8 [FEAT] 하단 네비게이션 바 추가
  package-lock.json
  package.json
  src/components/ui/Navbar/Navbar.styles.ts
  src/components/ui/Navbar/index.tsx
  src/layout/Layout.tsx
Labels: 💻 FE, 🚀 FEAT

#19 #16 [FEAT] 하단에서 올라오는 모달 컴포넌트를 퍼블리싱합니다.
  index.html
  src/components/ui/Modal/Modal.styles.ts
  src/components/ui/Modal/index.tsx
  src/constants/constant.ts
  src/hooks/.gitkeep
  src/hooks/useDrag.ts
  src/types/drag-handler.d.ts
Labels: 💻 FE, 🚀 FEAT

#21 #20 [FEAT] 탭 UI 컴포넌트 개발
  src/components/ui/Tab/Tab.styles.ts
  src/components/ui/Tab/index.tsx
Labels: 💻 FE, 🚀 FEAT

#28 #22 [FEAT]페이지 뒤로가기 네비게이션 UI 컴포넌트 개발
  src/components/ui/PageNav/PageNav.styles.ts
  src/components/ui/PageNav/index.tsx
Labels: 💻 FE, 🚀 FEAT
