Repository Dev-FE-2/toy-project2-team4-dayus, pull requests merged in 2024-12, with the labels that each got.

#31 #30 [FEAT] textarea컴포넌트 추가,label 컴포넌트 추가
  src/components/ui/Input/LabeledInput.tsx
  src/components/ui/Input/index.tsx
  src/components/ui/Label/LabeledBox.tsx
  src/components/ui/Label/index.tsx
  src/components/ui/Select/LabeledSelect.tsx
  src/components/ui/Select/index.tsx
  src/components/ui/Textarea/index.tsx
  src/styles/GlobalStyles.ts
  src/types/form.ts
  src/types/input.d.ts
  src/types/select.d.ts
Labels: 💻 FE, 🚀 FEAT

#29 #27 [FEAT] 스피너 컴포넌트를 퍼블리싱합니다.
  src/components/ui/Spinner/Spinner.styles.ts
  src/components/ui/Spinner/index.tsx
Labels: 💻 FE, 🚀 FEAT

#35 #32 [FEAT] 로그인 페이지 컴포넌트 UI 구현
  src/assets/logo.svg
  src/layout/Layout.styles.ts
  src/pages/LoginPage.tsx
  src/pages/login/LoginPage.styles.ts
  src/pages/login/LoginPage.tsx
  src/routes/Router.tsx
Labels: 💻 FE, 🚀 FEAT

#43 #34 [FEAT] React day-picker 라이브러리를 사용하여 DayPicker UI 컴포넌트를 퍼블리싱합니다.
  package-lock.json
  package.json
  src/components/ui/DayPicker/DayPicker.styles.ts
  src/components/ui/DayPicker/index.tsx
  src/types/day-picker.d.ts
Labels: 💻 FE, 🚀 FEAT

#40 #38 [docs]erd 사진 추가 및 docs 폴더 생성
  public/docs/dayus-erd.png
  public/docs/erd.md
Labels: 🔧 CHORE

#52 #49 [FEAT] 헤더 컴포넌트에 로고를 포함하여 퍼블리싱합니다.
  src/components/header/Header.styles.ts
  src/components/header/Header.tsx
  src/layout/Layout.tsx
Labels: 💻 FE, 🚀 FEAT

#48 #46 [FEAT] DayPicker 컴포넌트를 사용해 single 모드와 range 모드일 경우의 컴포넌트를 퍼블리싱합니다.
  src/components/day-picker/RangeDayPicker.styles.ts
  src/components/day-picker/RangeDayPicker.tsx
  src/components/day-picker/SingleDayPicker.styles.ts
  src/components/day-picker/SingleDayPicker.tsx
  src/components/header/Header.styles.ts
  src/components/header/Header.tsx
  src/components/ui/DayPicker/DayPicker.styles.ts
  src/layout/Layout.tsx
  src/utils/formatDate.ts
Labels: 💻 FE, 🚀 FEAT

#58 #47 [STYLE] 공통 레이아웃 및 로그인 UI 스타일 변경
  src/layout/Layout.styles.ts
  src/pages/login/LoginPage.styles.ts
Labels: 🌴 STYLE

#55 #45 [FEAT] 일정(메인)페이지 UI 작업
  package-lock.json
  package.json
  src/components/calendar/MainCalendar.style.ts
  src/components/calendar/MainCalendar.tsx
  src/mocks/data/calendar.ts
  src/pages/HomePage.tsx
  src/pages/home/HomePage.style.ts
  src/pages/home/HomePage.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyles.ts
  src/styles/design-tokens.css
  src/types/calendar.d.ts
  src/types/form.d.ts
Labels: 💻 FE, 🚀 FEAT

#54 #41 [FEAT] firebase를 이용해 로그인 기능 추가
  src/apis/firebase/firestore.ts
  src/layout/Layout.tsx
  src/pages/login/LoginForm.tsx
  src/pages/login/LoginPage.styles.ts
  src/pages/login/LoginPage.tsx
  src/types/form.d.ts
Labels: 🚀 FEAT, 🔩 SERVER

#61 #56 [FEAT] 일정 목록 모달을 퍼블리싱합니다.
  src/assets/empty-list.svg
  src/components/schdule/ScheduleItem.styles.ts
  src/components/schdule/ScheduleItem.tsx
  src/components/schdule/ScheduleList.styles.ts
  src/components/schdule/ScheduleList.tsx
  src/mocks/data/calendar.ts
  src/types/schedule.d.ts
Labels: 💻 FE, 🚀 FEAT

#60 #53 [FEAT] 무한 스크롤 기능 컴포넌트 개발
  src/components/infinite-scroll/InfiniteScroll.tsx
  src/components/list/ListItem.styles.ts
  src/components/list/SalaryItem.tsx
  src/components/list/SalaryList.styles.ts
  src/components/list/SalaryList.tsx
  src/types/infinite-scroll.ts
Labels: 🚀 FEAT

#66 #65 [FEAT] formatDate 함수 확장을 위한 타입, return 추가
  src/utils/formatDate.ts
Labels: 🚀 FEAT

#67 #62 [FEAT] 캘린더에서 셀 클릭 시 해당 날짜에 해당하는 리스트가 렌더링되도록 제작합니다.
  src/components/calendar/CustomToolbar.styles.ts
  src/components/calendar/CustomToolbar.tsx
  src/components/calendar/MainCalendar.style.ts
  src/components/calendar/MainCalendar.tsx
  src/components/schedule/schedule-item/ScheduleItem.styles.ts
  src/components/schedule/schedule-item/ScheduleItem.tsx
  src/components/schedule/schedule-list/ScheduleList.styles.ts
  src/components/schedule/schedule-list/ScheduleList.tsx
  src/mocks/data/calendar.ts
Labels: 💻 FE, 🚀 FEAT

#69 #68 [REFACTOR] 캘린더 이벤트로직을 커스텀 훅으로 분리합니다.
  src/components/calendar/MainCalendar.tsx
  src/hooks/useCalendarEvents.ts
Labels: 💻 FE, 🔨 REFACTOR

#73 #71 [CHORE] 파일 구조 변경
  src/apis/index.ts
  src/mocks/handlers.ts
  src/pages/login/LoginForm.tsx
  src/server/firebase/auth.ts
  src/server/firebase/initialize.ts
  src/server/handlers/exampleHandler.ts
  src/server/handlers/index.ts
Labels: 🔧 CHORE

#74 #71 [FEAT] mocking 준비를 위한 msw mock api 개발
  src/mocks/data/salary.ts
  src/server/handlers/index.ts
  src/server/handlers/salaryHandlers.ts
Labels: 🚀 FEAT, 🔩 SERVER

#75 #70 [FEAT] 이벤트 삭제 관련 로직을 추가합니다.
  src/components/calendar/MainCalendar.tsx
  src/components/schedule/schedule-item/ScheduleItem.styles.ts
  src/components/schedule/schedule-item/ScheduleItem.tsx
  src/components/schedule/schedule-list/ScheduleList.tsx
  src/hooks/useCalendarEvents.ts
  src/mocks/data/calendar.ts
  src/types/calendar.d.ts
  src/types/schedule.d.ts
  src/utils/compareDateRange.ts
  src/utils/formatDate.ts
Labels: 💻 FE, 🚀 FEAT

#77 feat: 급여 데이터 타입 모델링 + 데이터 정제를 위한 formatDate 유틸리티 함수 적용
  src/components/Accordion/SalaryAccordion.tsx
  src/components/list/SalaryItem.tsx
  src/components/list/SalaryList.tsx
  src/mocks/data/salary.ts
  src/types/salary.ts
Labels: 💻 FE, 🔨 REFACTOR

#79 #78 [STYLE] 일정 확인 모달 내부에서 일정 추가 버튼 스타일 수정하기
  src/components/schedule/schedule-list/ScheduleList.styles.ts
  src/components/schedule/schedule-list/ScheduleList.tsx
Labels: 💻 FE, 🌴 STYLE

#80 #77 [FEAT] 급여 정보 조회 api 개발 + 유틸리티 기능 추가
  src/api/axios.ts
  src/api/index.ts
  src/api/salaryApi.ts
  src/constants/constant.ts
  src/server/handlers/salaryHandlers.ts
  src/utils/apiUtils.ts
Labels: 💻 FE, 🚀 FEAT

#84 #63 [FEAT] 일정 추가 모달 UI 작업
  src/components/add-schedule-modal/AddScheduleModal.style.ts
  src/components/add-schedule-modal/AddScheduleModal.tsx
  src/components/color-picker/ColorPicker.style.ts
  src/components/color-picker/ColorPicker.tsx
  src/components/day-picker/RangeDayPicker.styles.ts
  src/components/day-picker/RangeDayPicker.tsx
  src/components/ui/Button/ColorPickerButton.tsx
  src/components/ui/Input/index.tsx
  src/components/ui/Modal/Modal.styles.ts
  src/components/ui/Modal/index.tsx
  src/components/ui/ModalFull/ModalFull.style.ts
  src/components/ui/ModalFull/index.tsx
  src/components/ui/PageNav/PageNav.styles.ts
  src/components/ui/PageNav/index.tsx
  src/constants/constant.ts
  src/hooks/useScrollLock.ts
  src/layout/Layout.styles.ts
  src/mocks/data/calendar.ts
  src/pages/home/HomePage.tsx
  src/styles/GlobalStyles.ts
  src/styles/design-tokens.css
  src/types/button.ts
Labels: 💻 FE

#92 #91 [CHORE] d.ts 확장자를 ts 확장자로 변경합니다.
  src/types/calendar.ts
  src/types/day-picker.ts
  src/types/drag-handler.ts
  src/types/form.ts
  src/types/schedule.ts
Labels: 🔧 CHORE

#95 [FEAT] 모달 여닫는 state를 redux slice로 제작
  src/components/schedule/schedule-list/ScheduleList.tsx
  src/components/ui/ModalFull/index.tsx
  src/constants/constant.ts
  src/hooks/useToggleModal.ts
  src/main.tsx
  src/pages/home/HomePage.tsx
  src/store/index.ts
  src/store/slices/modalToggleSlice.ts
Labels: 💻 FE, 🚀 FEAT

#89 #88 [FEAT] 로그인 한 유저만 접속 가능한 보호된 라우트 적용
  src/App.tsx
  src/components/ProtectedRoute/ProtectedRoute.tsx
  src/pages/login/LoginPage.tsx
  src/routes/Router.tsx
Labels: 💻 FE, 🚀 FEAT

#96 #93 [FEAT] 캘린더 일정 수정 모달 컴포넌트를 제작합니다.
  src/components/calendar/MainCalendar.tsx
  src/components/color-picker/ColorPicker.tsx
  src/components/day-picker/RangeDayPicker.tsx
  src/components/edit-schedule-modal/EditScheduleModal.styles.ts
  src/components/edit-schedule-modal/EditScheduleModal.tsx
  src/components/schedule/schedule-item/ScheduleItem.styles.ts
  src/components/schedule/schedule-item/ScheduleItem.tsx
  src/components/schedule/schedule-list/ScheduleList.styles.ts
  src/components/schedule/schedule-list/ScheduleList.tsx
  src/constants/constant.ts
  src/hooks/useCalendarEvents.ts
  src/hooks/useDebounce.ts
  src/types/calendar.ts
  src/types/color-picker.ts
  src/types/day-picker.ts
  src/types/form.ts
  src/types/schedule.ts
  src/utils/compareDateRange.ts
Labels: 💻 FE, 🚀 FEAT

#105 #104 [FIX] 풀모달을 사용 시 발생하는 무한 렌더링 문제를 해결합니다.
  src/components/calendar/MainCalendar.tsx
  src/components/ui/ModalFull/index.tsx
  src/hooks/useToggleModal.ts
Labels: 🚀 FEAT, 🚨 HOTFIX

#101 #100 [FEAT] 마이페이지 컴포넌트 UI 구현 및 버튼 컴포넌트 outline 형태 추가
  src/assets/user.svg
  src/components/ui/Button/Button.tsx
  src/layout/Layout.tsx
  src/pages/ProfilePage.tsx
  src/pages/profile-page/ProfilePage.styles.ts
  src/pages/profile-page/ProfilePage.tsx
  src/routes/Router.tsx
Labels: 💻 FE, 🚀 FEAT

#103 #102 [HOTFIX] router.tsx 파일 내부의 provider 관련 코드 제거
  src/routes/Router.tsx
Labels: 🚨 HOTFIX

#97 #90 [FEAT] 급여 목록 페이지의 컴포넌트 취합 및 ESLint 에러에 대한 수정
  src/api/salaryApi.ts
  src/components/Accordion/SalaryAccordion.tsx
  src/components/Modal/SalaryModal.tsx
  src/components/accordion/SalaryAccordion.styles.ts
  src/components/accordion/SalaryAccordion.tsx
  src/components/infinite-scroll/InfiniteScroll.tsx
  src/components/list/ListItem.styles.ts
  src/components/list/SalaryItem.tsx
  src/components/list/SalaryList.styles.ts
  src/components/list/SalaryList.tsx
  src/components/modal/SalaryModal.styles.ts
  src/components/modal/SalaryModal.tsx
  src/constants/constant.ts
  src/hooks/useSalaryItem.ts
  src/hooks/useSalaryList.ts
  src/mocks/data/salary.ts
  src/pages/SalaryPage.tsx
  src/pages/salary/SalaryPage.styles.tsx
  src/pages/salary/SalaryPage.tsx
  src/routes/Router.tsx
  src/types/salary.ts
  src/utils/arrayUtils.ts
  src/utils/formatSalaryDetail.ts
Labels: 💣 BUG, 💻 FE, 🚀 FEAT

#99 #98 [FEAT] 근무 정정 정보 조회 페이지 개발
  src/api/shiftApi.ts
  src/components/list/ShiftItem.tsx
  src/components/list/ShiftList.tsx
  src/constants/constant.ts
  src/hooks/useShiftList.ts
  src/mocks/data/shift.ts
  src/pages/shift/ShiftPage.styles.ts
  src/pages/shift/ShiftPage.tsx
  src/routes/Router.tsx
  src/server/handlers/index.ts
  src/server/handlers/shiftHandler.ts
  src/types/shift.ts
Labels: 💻 FE, 🚀 FEAT

#108 #106 [REFACTOR] 풀모달을 홈페이지에서 관리하도록 리팩토링합니다.
  src/components/calendar/MainCalendar.tsx
  src/components/schedule/schedule-item/ScheduleItem.tsx
  src/components/schedule/schedule-list/ScheduleList.tsx
  src/pages/home/HomePage.tsx
  src/types/calendar.ts
  src/types/schedule.ts
Labels: 🚀 FEAT, 🔨 REFACTOR

#112 [FEAT] 일정 데이터를 모킹하기 위한 API를 추가합니다.
  src/api/calendarApi.ts
  src/server/handlers/calendarHandlers.ts
  src/server/handlers/index.ts
Labels: 💻 FE, 🚀 FEAT

#114 [STYLE] 달력에서 토요일 관련한 스타일을 수정합니다.
  src/components/calendar/MainCalendar.style.ts
Labels: 💣 BUG, 🌴 STYLE

#116 [FEAT] firestore와 연결하여 일정 조회, 삭제, 수정을 구현합니다.
  src/api/scheduleApi.ts
  src/components/calendar/MainCalendar.style.ts
  src/hooks/useCalendarEvents.ts
  src/pages/home/HomePage.style.ts
  src/pages/home/HomePage.tsx
Labels: 💻 FE, 🚀 FEAT

#119 [STYLE] navbar 스타일 수정
  src/components/ui/Navbar/Navbar.styles.ts
  src/styles/design-tokens.css
Labels: 🌴 STYLE

#120 #118 [FEAT] 개인 일정이 아닌 근무 일정을 firestore와 연동해 조회하고, 수정은 불가능하도록 합니다.
  src/api/scheduleApi.ts
  src/components/schedule/schedule-item/ScheduleItem.styles.ts
  src/components/schedule/schedule-item/ScheduleItem.tsx
  src/constants/constant.ts
  src/hooks/useCalendarEvents.ts
Labels: 💻 FE, 🚀 FEAT

#124 #123 [FEAT] 메인 캘린더 하단에 카페 행사 정보를 조회합니다.
  src/api/cafeScheduleApi.ts
  src/components/cafe-events/CafeEventCard.styles.ts
  src/components/cafe-events/CafeEventCard.tsx
  src/components/cafe-events/CafeEvents.styles.ts
  src/components/cafe-events/CafeEvents.tsx
  src/pages/home/HomePage.tsx
  src/types/calendar.ts
Labels: 💻 FE, 🚀 FEAT

#127 #126 [DOCS] 리드미를 업데이트합니다.
  README.md
Labels: 🔧 CHORE

#129 #128 [FEAT] 급여 목록 mock api를 firestore로 변경
  src/api/salaryApi.ts
  src/hooks/useSalaryItem.ts
  src/hooks/useSalaryList.ts
Labels: 💻 FE, 🚀 FEAT

#122 #94 [FEAT] 일정 추가 모달 개발
  src/api/scheduleApi.ts
  src/components/add-schedule-modal/AddScheduleModal.style.ts
  src/components/add-schedule-modal/AddScheduleModal.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/schedule/schedule-list/ScheduleList.styles.ts
  src/components/schedule/schedule-list/ScheduleList.tsx
  src/hooks/useCalendarEvents.ts
  src/pages/home/HomePage.tsx
  src/pages/login/LoginPage.styles.ts
  src/types/calendar.ts
  src/types/schedule.ts
  src/utils/getRandomString.ts
Labels: 💻 FE, 🚀 FEAT

#125 #109 [FEAT] 마이페이지 수정 풀모달 개발
  src/api/profileApi.ts
  src/components/full-modal/ProfileModal.styles.ts
  src/components/full-modal/ProfileModal.tsx
  src/constants/constant.ts
  src/pages/profile-page/ProfilePage.tsx
  src/types/profile-modal.ts
Labels: 💻 FE, 🚀 FEAT

#131 #130 [HOTFIX] 일정 추가 모달에서 일정을 추가할 시 리스트에 바로 반영되지 않는 오류를 수정합니다.
  src/hooks/useCalendarEvents.ts
Labels: 💻 FE, 🚨 HOTFIX

#133 #132 [FIX] 급여 정보 조회를 위한 모달창의 UI 구조를 변경하고 제목을 추가
  src/components/modal/SalaryModal.styles.ts
  src/components/modal/SalaryModal.tsx
  src/pages/salary/SalaryPage.tsx
Labels: 💻 FE, 🌴 STYLE

#137 #136 [FIX] 근무 정정 신청 결과에 따른 팝업을 위한 react hot toast 추가 구현
  package-lock.json
  package.json
  src/api/shiftApi.ts
  src/components/shift-modal/ShiftModal.tsx
  src/pages/shift/ShiftPage.tsx
Labels: 💻 FE, 🚀 FEAT, 🚨 HOTFIX

#144 #143 [FEAT] 일정 추가, 조회, 삭제에 react-hot-toast를 추가합니다.
  src/App.tsx
  src/api/scheduleApi.ts
  src/api/shiftApi.ts
  src/components/add-schedule-modal/AddScheduleModal.tsx
  src/pages/shift/ShiftPage.tsx
  src/utils/getRandomString.ts
  src/utils/toast.ts
Labels: 💻 FE, 🚀 FEAT

#147 [REFACTOR] 캘린더 일정 조회, 삭제, 수정, 추가를 전역 상태로 관리합니다.
  src/components/add-schedule-modal/AddScheduleModal.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/edit-schedule-modal/EditScheduleModal.tsx
  src/components/schedule/schedule-item/ScheduleItem.tsx
  src/components/schedule/schedule-list/ScheduleList.tsx
  src/hooks/useCalendarActions.ts
  src/hooks/useCalendarEvents.ts
  src/pages/home/HomePage.tsx
  src/store/index.ts
  src/store/slices/calendarSlice.ts
  src/types/calendar.ts
  src/types/schedule.ts
Labels: 💻 FE, 🔨 REFACTOR

#149 #148 [REFACTOR] 테스트하며 생긴 일정 수정 로직을 수정합니다.
  src/components/edit-schedule-modal/EditScheduleModal.tsx
  src/components/schedule/schedule-item/ScheduleItem.tsx
  src/pages/home/HomePage.tsx
  src/store/slices/calendarSlice.ts
Labels: 💻 FE, 🔨 REFACTOR

#151 #150 [CHORE] 폴더 네이밍을 통일합니다.
  src/App.tsx
  src/components/accordion/SalaryAccordion.tsx
  src/components/add-schedule-modal/AddScheduleModal.tsx
  src/components/cafe-events/CafeEvents.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/color-picker/ColorPicker.tsx
  src/components/day-picker/RangeDayPicker.tsx
  src/components/day-picker/SingleDayPicker.styles.ts
  src/components/day-picker/SingleDayPicker.tsx
  src/components/edit-schedule-modal/EditScheduleModal.tsx
  src/components/full-modal/ProfileModal.tsx
  src/components/infinite-scroll/InfiniteScroll.tsx
  src/components/list/ShiftList.tsx
  src/components/modal/SalaryModal.tsx
  src/components/protected-route/ProtectedRoute.tsx
  src/components/schedule/schedule-item/ScheduleItem.tsx
  src/components/shift-modal/ShiftModal.styles.ts
  src/components/shift-modal/ShiftModal.tsx
  src/components/ui/day-picker/DayPicker.styles.ts
  src/components/ui/day-picker/index.tsx
  src/components/ui/modal-full/ModalFull.style.ts
  src/components/ui/modal-full/index.tsx
  src/components/ui/navigation/Navbar.styles.ts
  src/components/ui/navigation/index.tsx
  src/components/ui/page-navigation/PageNav.styles.ts
  src/components/ui/page-navigation/index.tsx
  src/layout/Layout.tsx
  src/pages/home/HomePage.tsx
  src/pages/login/LoginForm.tsx
  src/pages/not-found/NotFoundPage.tsx
  src/pages/profile-page/ProfilePage.tsx
  src/pages/salary/SalaryPage.tsx
  src/pages/shift/ShiftPage.tsx
  src/routes/Router.tsx
  src/types/day-picker.ts
Labels: 🔧 CHORE

#152 [FIX] 대소문자 무시하는 오류 수정
  src/components/ui/accordion/Accordion.styles.ts
  src/components/ui/accordion/index.tsx
  src/components/ui/button/Button.tsx
  src/components/ui/button/ColorPickerButton.tsx
  src/components/ui/input/index.tsx
  src/components/ui/label/LabeledBox.tsx
  src/components/ui/label/index.tsx
  src/components/ui/modal/Modal.styles.ts
  src/components/ui/modal/index.tsx
  src/components/ui/select/Select.styles.ts
  src/components/ui/select/index.tsx
  src/components/ui/spinner/Spinner.styles.ts
  src/components/ui/spinner/index.tsx
  src/components/ui/tab/Tab.styles.ts
  src/components/ui/tab/index.tsx
  src/components/ui/textarea/index.tsx
Labels: 🚨 HOTFIX
